### ISSUE TITLE
TODO Notes

### ISSUE THREAD

**Issue by Okanmercan99** [AI4HF/passport-web#10]
- [ ] Implemenet not found page routings.
- [ ] Change translateService.instant() usages into translateService.get().
- [x] Population does not show in population detail menu.
- [x] Percentage should refuse string input in Learning stage form.
- [ ] Update all id field data types to string from long.

**Comment by KeremHmd** [comment]
- [ ] Connect current user's organization to model creation body data at Model Management Form.
